name: Python application

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with unittest
      run: |
        python -m unittest test_app.py -v
    
    - name: Check Flask app runs
      run: |
        python -c "import app; print('Flask app imports successfully')"
    
    - name: Check dependencies
      run: |
        python -c "import flask, groq, dotenv; print('All required packages available')"

  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install Bandit
      run: |
        python -m pip install --upgrade pip
        pip install bandit
    
    - name: Run Bandit security linter
      run: |
        bandit -r . -f json -o bandit-report.json || true
    
    - name: Check for critical security issues
      run: |
        bandit -r . -f json -o bandit-report.json -ll || true
        # Only fail if critical issues are found
        if [ -f bandit-report.json ]; then
          python -c "
          import json
          try:
              with open('bandit-report.json', 'r') as f:
                  data = json.load(f)
                  critical_issues = [i for i in data.get('results', []) if i.get('issue_severity') == 'HIGH']
                  if critical_issues:
                      print(f'Found {len(critical_issues)} critical security issues')
                      exit(1)
                  else:
                      print('No critical security issues found')
          except Exception as e:
              print(f'Error parsing bandit report: {e}')
              exit(0)
          "
        fi
